### ISSUE TITLE
Question about data preprocessing

### ISSUE THREAD

**Issue by CinKKKyo** [Shrajan/IB_U_Nets#1]
I found that in MSD-Prostate Dataset, the pixel spacing is not the same between the image and labels, so it is impossible to change them in a new pixel spacing while maintaining the same image size in the current script. How do you deal with it?

**Comment by Shrajan** [comment]
Hi @CinKKKyo, in the MSD-prostate dataset, the image is 4D with two channels (T2, ADC), whereas, the label is 3D. Is this what you mean by “the pixel spacing is not the same between the image and labels”? If yes, then please note, as mentioned in the paper, we only consider T2-weighted channel and not the ADC. I hope this helps.

**Comment by CinKKKyo** [comment]
While I mean every sample in MSD-Prostate has a different pixel spacing between the image and label, like the following:
![image](https://github.com/Shrajan/IB_U_Nets/assets/40874032/9e6a3f22-0bb1-403b-a7f2-1d1feccc7682)
row1 & row3 represent the pixel spacing of the image and label from one sample, they should be equal but actually not, so how do you process MSD-Prostate? Thanks for your help

**Comment by Shrajan** [comment]
Hello @CinKKKyo. It appears you have the wrong dataset, because you should get the following outputs:

<img width="914" alt="MSD_prostate_preprocessing" src="https://github.com/Shrajan/IB_U_Nets/assets/25223127/2a79e787-1fc9-4dc5-99aa-fa6fb72ac7e6">

Please download the correct version from here: http://medicaldecathlon.com.
